# Generated by Django 4.2.7 on 2023-12-04 00:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import order.models
import utils.code


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(max_length=250, verbose_name='address')),
                ('additional', models.TextField(blank=True, help_text='May to contains some personal and another important info', max_length=250, verbose_name='additional info')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'form',
                'verbose_name_plural': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
            ],
            options={
                'verbose_name': 'size',
                'verbose_name_plural': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(default=utils.code.generate_code, editable=False, max_length=40, primary_key=True, serialize=False, verbose_name='code')),
                ('status', models.CharField(choices=[('returned', 'Returned'), ('cancelled', 'Cancelled'), ('in_process', 'In Process'), ('completed', 'Completed')], default='in_process', max_length=15, verbose_name='status')),
                ('process', models.CharField(choices=[('pending', 'Expects the manager to accept it'), ('in_assembly', 'In Assembly'), ('in_delivery', 'In Delivery'), ('delivered', 'Delivered')], default='in_assembly', max_length=15, verbose_name='process status')),
                ('comment', models.TextField(blank=True, max_length=250, verbose_name='comment')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.client', verbose_name='client')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.color', verbose_name='color')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.form', verbose_name='form')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'permissions': [('view_any_status', 'Can view an order with any status'), ('view_in_assembly_only', 'Can view an order with `in assembly` status only'), ('view_in_delivery_only', 'Can view an order with `in delivery` status only')],
            },
        ),
        migrations.CreateModel(
            name='StandardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.color', verbose_name='color')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.form', verbose_name='form')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.size', verbose_name='size')),
            ],
            options={
                'verbose_name': 'standard order properties',
                'verbose_name_plural': 'standard orders properties',
            },
        ),
        migrations.CreateModel(
            name='OrderReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('solution', models.CharField(choices=[('money', 'return money to the client'), ('new_order', 'create a new order to replace the returned one')], max_length=15, verbose_name='solution')),
                ('new_order', models.OneToOneField(default=None, help_text='Set new `Order` instance if the solution is `new order`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_for', to='order.order', verbose_name='new order')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order', validators=[order.models.validate_order_is_returned], verbose_name='order')),
            ],
            options={
                'verbose_name': 'return order solution',
                'verbose_name_plural': 'return order solutions',
            },
        ),
    ]
