# Generated by Django 4.2.7 on 2023-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreturn',
            name='solution',
            field=models.CharField(choices=[('pending', 'pending'), ('money', 'return money to the client'), ('new_order', 'create a new order to replace the returned one')], default='pending', max_length=15, verbose_name='solution'),
        ),
    ]
